### ISSUE TITLE
Request tutorials about yarpmanager 

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_yarpmanager#1]
On a physical robot, we used the yarpmanager to manage the files below. E.g. I want to find the original C++ files (uncompiled), what should I do?
 
![image](https://user-images.githubusercontent.com/55526431/71963900-f603e400-323f-11ea-97a8-c49c1a61e730.png)

In addition, I noted that on the right of the figure, there is an option called Parameters as follows. It is strange that on my computer, I cannot find the file called dragonfly2_config_left_bayer_640_480.ini and even cannot find the folder named camera. 
Where are these files? 
 
![image](https://user-images.githubusercontent.com/55526431/71963910-fa300180-323f-11ea-9cf8-a07e73b7ca9f.png)

In addition, I try to use the terminal to configure settings. Type on the terminal.
$ yarpview --from  camera/ dragonfly2_config_left_bayer_640_480.ini
but failed as follow. How do I configure these settings if I want to use the terminal?

![image](https://user-images.githubusercontent.com/55526431/71963925-fe5c1f00-323f-11ea-86ae-057fd577d4a4.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

This issue is unrelated to this repository. As I mentioned several times, it's quite important for us to keep things neat and open tickets in the right location 😉 

The organization `vvv-school` is meant for our School, meaning it contains tutorials and assignments that we run during the school. Instead, this is a very general question, thus please open it in https://github.com/robotology/QA/issues. Thanks!
